#!/bin/bash
filename="$(date +%d-%b-flameshot)-$RANDOM.png"
flameshot gui -r > ~/dox/pics/$filename
curl -H "Content-Type: multipart/form-data" -H "embed: true" -H "authorization: yourtoken" -F file="@/home/neb/dox/pics/$filename" https://i.neb.cx/api/upload | jq -r '.files | .[]' | tr -d '\n' | xsel -b
